<a href="https://colab.research.google.com/github/M339KUMAR/ColabDemoFiles/blob/main/UMDAP2/UMDAP2%20May-26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PALO ALTO HR Analytics

####Importing Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = '/content/sample_data/Palo Alto Networks.xlsx'

In [3]:
df = pd.read_excel(path)
df.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   object
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   object
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   object
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   object
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(24), object(7)
memory usage: 356.1+ KB

In [5]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [6]:
df.describe(include='object').T

               count unique                     top  freq
BusinessTravel  1470      3           Travel_Rarely  1043
Department      1470      3  Research & Development   961
EducationField  1470      6           Life Sciences   606
Gender          1470      2                    Male   882
JobRole         1470      9         Sales Executive   326
MaritalStatus   1470      3                 Married   673
OverTime        1470      2                      No  1054

In [7]:
df.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.0,36.0,43.00,60.0
Attrition,1470.0,0.161224,0.367863,0.0,0.0,0.0,0.00,1.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.0,802.0,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.0,7.0,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.0,3.0,4.00,5.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.0,3.0,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.0,66.0,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.0,3.0,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.0,2.0,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.0,3.0,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.0,4919.0,8379.00,19999.0
MonthlyRate,1470.0,14313.103401,7117.786044,2094.0,8047.0,14235.5,20461.50,26999.0
NumCompaniesWorked,1470.0,2.693197,2.498009,0.0,1.0,2.0,4.00,9.0
PercentSalaryHike,1470.0,15.209524,3.659938,11.0,12.0,14.0,18.00,25.0
PerformanceRating,1470.0,3.153741,0.360824,3.0,3.0,3.0,3.00,4.0
RelationshipSatisfaction,1470.0,2.712245,1.081209,1.0,2.0,3.0,4.00,4.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.0,1.0,1.00,3.0
TotalWorkingYears,1470.0,11.279592,7.780782,0.0,6.0,10.0,15.00,40.0
TrainingTimesLastYear,1470.0,2.799320,1.289271,0.0,2.0,3.0,3.00,6.0
WorkLifeBalance,1470.0,2.761224,0.706476,1.0,2.0,3.0,3.00,4.0
YearsAtCompany,1470.0,7.008163,6.126525,0.0,3.0,5.0,9.00,40.0
YearsInCurrentRole,1470.0,4.229252,3.623137,0.0,2.0,3.0,7.00,18.0
YearsSinceLastPromotion,1470.0,2.187755,3.222430,0.0,0.0,1.0,3.00,15.0
YearsWithCurrManager,1470.0,4.123129,3.568136,0.0,2.0,3.0,7.00,17.0

In [8]:
df.select_dtypes(include='number').columns

Index(['Age', 'Attrition', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [42]:
for col in df.select_dtypes('number').columns:
    print()
    print(f'Value Counts in :: {col} of type :: {type(col)}')
    print(df[col].value_counts().sort_values())
    print(f'Minimum:{df[col].value_counts().min()} & Maximum:{df[col].value_counts().max()}')
    print(f'Minimum:{df[col].min()} & Maximum:{df[col].max()}')
    print(f'Shape of the Column:{df[col].shape}')
    print(f'Data Type of {col}:: {df[col].dtype}')
    print('----------------------')

print()
print('Total Number of Int & Float Columns::',df.select_dtypes('number').columns.shape[0])

Value Counts in :: Age of type :: <class 'str'>
Age
57     4
60     5
18     8
19     9
59    10
20    11
21    13
58    14
56    14
23    14
22    16
54    18
52    18
51    19
48    19
53    19
55    22
49    24
47    24
25    26
24    26
50    30
43    32
44    33
46    33
26    39
41    40
45    41
39    42
42    46
27    48
28    48
37    50
40    57
38    58
33    58
30    60
32    61
29    68
36    69
31    69
34    77
35    78
Name: count, dtype: int64
Minimum:4 & Maximum:78
Minimum:18 & Maximum:60
Shape of the Column:(1470,)
Data Type of Age:: int64
----------------------

Value Counts in :: Attrition of type :: <class 'str'>
Attrition
1     237
0    1233
Name: count, dtype: int64
Minimum:237 & Maximum:1233
Minimum:0 & Maximum:1
Shape of the Column:(1470,)
Data Type of Attrition:: int64
----------------------

Value Counts in :: DailyRate of type :: <class 'str'>
DailyRate
983     1
1274    1
657     1
376     1
384     1
       ..
329     5
1329    5
408     5
530     5
691     6
Name: count, Length: 886, dtype: int64
Minimum:1 & Maximum:6
Minimum:102 & Maximum:1499
Shape of the Column:(1470,)
Data Type of DailyRate:: int64
----------------------

Value Counts in :: DistanceFromHome of type :: <class 'str'>
DistanceFromHome
27     12
21     18
13     19
22     19
17     20
12     20
14     21
19     22
28     23
25     25
20     25
26     25
15     26
18     26
23     27
29     27
24     28
11     29
16     32
6      59
4      64
5      65
8      80
7      84
3      84
9      85
10     86
1     208
2     211
Name: count, dtype: int64
Minimum:12 & Maximum:211
Minimum:1 & Maximum:29
Shape of the Column:(1470,)
Data Type of DistanceFromHome:: int64
----------------------

Value Counts in :: Education of type :: <class 'str'>
Education
5     48
1    170
2    282
4    398
3    572
Name: count, dtype: int64
Minimum:48 & Maximum:572
Minimum:1 & Maximum:5
Shape of the Column:(1470,)
Data Type of Education:: int64
----------------------

Value Counts in :: EnvironmentSatisfaction of type :: <class 'str'>
EnvironmentSatisfaction
1    284
2    287
4    446
3    453
Name: count, dtype: int64
Minimum:284 & Maximum:453
Minimum:1 & Maximum:4
Shape of the Column:(1470,)
Data Type of EnvironmentSatisfaction:: int64
----------------------

Value Counts in :: HourlyRate of type :: <class 'str'>
HourlyRate
34    12
38    13
68    14
53    14
69    15
      ..
84    28
42    28
98    28
48    28
66    29
Name: count, Length: 71, dtype: int64
Minimum:12 & Maximum:29
Minimum:30 & Maximum:100
Shape of the Column:(1470,)
Data Type of HourlyRate:: int64
----------------------

Value Counts in :: JobInvolvement of type :: <class 'str'>
JobInvolvement
1     83
4    144
2    375
3    868
Name: count, dtype: int64
Minimum:83 & Maximum:868
Minimum:1 & Maximum:4
Shape of the Column:(1470,)
Data Type of JobInvolvement:: int64
----------------------

Value Counts in :: JobLevel of type :: <class 'str'>
JobLevel
5     69
4    106
3    218
2    534
1    543
Name: count, dtype: int64
Minimum:69 & Maximum:543
Minimum:1 & Maximum:5
Shape of the Column:(1470,)
Data Type of JobLevel:: int64
----------------------

Value Counts in :: JobSatisfaction of type :: <class 'str'>
JobSatisfaction
2    280
1    289
3    442
4    459
Name: count, dtype: int64
Minimum:280 & Maximum:459
Minimum:1 & Maximum:4
Shape of the Column:(1470,)
Data Type of JobSatisfaction:: int64
----------------------

Value Counts in :: MonthlyIncome of type :: <class 'str'>
MonthlyIncome
9884     1
13503    1
5441     1
5209     1
10673    1
        ..
2451     3
2610     3
2559     3
3452     3
2342     4
Name: count, Length: 1349, dtype: int64
Minimum:1 & Maximum:4
Minimum:1009 & Maximum:19999
Shape of the Column:(1470,)
Data Type of MonthlyIncome:: int64
----------------------

Value Counts in :: MonthlyRate of type :: <class 'str'>
MonthlyRate
18775    1
13243    1
2396     1
4306     1
8232     1
        ..
20364    2
21981    2
9129     2
9150     3
4223     3
Name: count, Length: 1427, dtype: int64
Minimum:1 & Maximum:3
Minimum:2094 & Maximum:26999
Shape of the Column:(1470,)
Data Type of MonthlyRate:: int64
----------------------

Value Counts in :: NumCompaniesWorked of type :: <class 'str'>
NumCompaniesWorked
8     49
9     52
5     63
6     70
7     74
4    139
2    146
3    159
0    197
1    521
Name: count, dtype: int64
Minimum:49 & Maximum:521
Minimum:0 & Maximum:9
Shape of the Column:(1470,)
Data Type of NumCompaniesWorked:: int64
----------------------

Value Counts in :: PercentSalaryHike of type :: <class 'str'>
PercentSalaryHike
25     18
24     21
23     28
21     48
20     55
22     56
19     76
16     78
17     82
18     89
15    101
12    198
14    201
13    209
11    210
Name: count, dtype: int64
Minimum:18 & Maximum:210
Minimum:11 & Maximum:25
Shape of the Column:(1470,)
Data Type of PercentSalaryHike:: int64
----------------------

Value Counts in :: PerformanceRating of type :: <class 'str'>
PerformanceRating
4     226
3    1244
Name: count, dtype: int64
Minimum:226 & Maximum:1244
Minimum:3 & Maximum:4
Shape of the Column:(1470,)
Data Type of PerformanceRating:: int64
----------------------

Value Counts in :: RelationshipSatisfaction of type :: <class 'str'>
RelationshipSatisfaction
1    276
2    303
4    432
3    459
Name: count, dtype: int64
Minimum:276 & Maximum:459
Minimum:1 & Maximum:4
Shape of the Column:(1470,)
Data Type of RelationshipSatisfaction:: int64
----------------------

Value Counts in :: StockOptionLevel of type :: <class 'str'>
StockOptionLevel
3     85
2    158
1    596
0    631
Name: count, dtype: int64
Minimum:85 & Maximum:631
Minimum:0 & Maximum:3
Shape of the Column:(1470,)
Data Type of StockOptionLevel:: int64
----------------------

Value Counts in :: TotalWorkingYears of type :: <class 'str'>
TotalWorkingYears
38      1
40      2
35      3
37      4
34      5
36      6
30      7
33      7
27      7
31      9
32      9
29     10
0      11
26     14
25     14
28     14
24     18
22     21
19     22
23     22
18     27
20     30
14     31
2      31
17     33
21     34
11     36
13     36
16     37
15     40
3      42
12     48
4      63
7      81
1      81
5      88
9      96
8     103
6     125
10    202
Name: count, dtype: int64
Minimum:1 & Maximum:202
Minimum:0 & Maximum:40
Shape of the Column:(1470,)
Data Type of TotalWorkingYears:: int64
----------------------

Value Counts in :: TrainingTimesLastYear of type :: <class 'str'>
TrainingTimesLastYear
0     54
6     65
1     71
5    119
4    123
3    491
2    547
Name: count, dtype: int64
Minimum:54 & Maximum:547
Minimum:0 & Maximum:6
Shape of the Column:(1470,)
Data Type of TrainingTimesLastYear:: int64
----------------------

Value Counts in :: WorkLifeBalance of type :: <class 'str'>
WorkLifeBalance
1     80
4    153
2    344
3    893
Name: count, dtype: int64
Minimum:80 & Maximum:893
Minimum:1 & Maximum:4
Shape of the Column:(1470,)
Data Type of WorkLifeBalance:: int64
----------------------

Value Counts in :: YearsAtCompany of type :: <class 'str'>
YearsAtCompany
30      1
34      1
40      1
37      1
27      2
29      2
36      2
23      2
32      3
31      3
25      4
26      4
33      5
24      6
17      9
19     11
16     12
18     13
12     14
21     14
22     15
14     18
15     20
13     24
20     27
11     32
0      44
6      76
8      80
9      82
7      90
4     110
10    120
2     127
3     128
1     171
5     196
Name: count, dtype: int64
Minimum:1 & Maximum:196
Minimum:0 & Maximum:40
Shape of the Column:(1470,)
Data Type of YearsAtCompany:: int64
----------------------

Value Counts in :: YearsInCurrentRole of type :: <class 'str'>
YearsInCurrentRole
18      2
17      4
16      7
15      8
12     10
14     11
13     14
11     22
10     29
5      36
6      37
1      57
9      67
8      89
4     104
3     135
7     222
0     244
2     372
Name: count, dtype: int64
Minimum:2 & Maximum:372
Minimum:0 & Maximum:18
Shape of the Column:(1470,)
Data Type of YearsInCurrentRole:: int64
----------------------

Value Counts in :: YearsSinceLastPromotion of type :: <class 'str'>
YearsSinceLastPromotion
10      6
14      9
12     10
13     10
15     13
9      17
8      18
11     24
6      32
5      45
3      52
4      61
7      76
2     159
1     357
0     581
Name: count, dtype: int64
Minimum:6 & Maximum:581
Minimum:0 & Maximum:15
Shape of the Column:(1470,)
Data Type of YearsSinceLastPromotion:: int64
----------------------

Value Counts in :: YearsWithCurrManager of type :: <class 'str'>
YearsWithCurrManager
16      2
15      5
14      5
17      7
13     14
12     18
11     22
10     27
6      29
5      31
9      64
1      76
4      98
8     107
3     142
7     216
0     263
2     344
Name: count, dtype: int64
Minimum:2 & Maximum:344
Minimum:0 & Maximum:17
Shape of the Column:(1470,)
Data Type of YearsWithCurrManager:: int64
----------------------

Total Number of Int & Float Columns:: 24

In [20]:
for col in df.select_dtypes('object').columns:
    print(f'Value Counts in :: {col}')
    print('----------------------')
    print(df[col].value_counts())
    print('----------------------')

print()
print(f'Total number of Object colmns:{df.select_dtypes('object').columns.shape[0]}')

Value Counts in :: BusinessTravel
----------------------
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64
----------------------
Value Counts in :: Department
----------------------
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64
----------------------
Value Counts in :: EducationField
----------------------
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64
----------------------
Value Counts in :: Gender
----------------------
Gender
Male      882
Female    588
Name: count, dtype: int64
----------------------
Value Counts in :: JobRole
----------------------
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64
----------------------
Value Counts in :: MaritalStatus
----------------------
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64
----------------------
Value Counts in :: OverTime
----------------------
OverTime
No     1054
Yes     416
Name: count, dtype: int64
----------------------

7