<a href="https://colab.research.google.com/github/M339KUMAR/ColabDemoFiles/blob/main/MTE%20DA/MTE_DA_Apr2026(Apr19th-1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Left Handers DataSet Analytics

### 1.Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import openpyxl as xl
import numpy as np

%matplotlib inline

###2.Loading the Data

In [3]:
#Left Handers Data
data_url_1 = '/content/sample_data/lh_data.txt'

#Death Distribution Data
data_url_2 = '/content/sample_data/cdc_vs00199_table310.tsv'

In [5]:
df1= pd.read_csv(data_url_1)
df1

    Age       Male     Female
0    10  12.717558  12.198041
1    11  15.318830  11.144804
2    12  14.808281  11.549240
3    13  13.793744  11.276442
4    14  15.156304  11.572906
..  ...        ...        ...
72   82   7.350204   4.874899
73   83   6.471204   5.672536
74   84   6.510858   5.774881
75   85   7.337968   7.051459
76   86   5.059387   4.680948

[77 rows x 3 columns]

In [8]:
df2 = pd.read_csv(data_url_2, sep='\t')
df2

     Age  Both Sexes       Male     Female
0    ALL   2391399.0  1175460.0  1215939.0
1      0     27937.0    15646.0    12291.0
2      1      1989.0     1103.0      886.0
3      2      1376.0      797.0      579.0
4      3      1046.0      601.0      445.0
..   ...         ...        ...        ...
121  120         1.0        NaN        1.0
122  121         NaN        NaN        NaN
123  122         NaN        NaN        NaN
124  123         NaN        NaN        NaN
125  124         NaN        NaN        NaN

[126 rows x 4 columns]

In [10]:
df3 = pd.read_csv(data_url_2, sep='\t', skiprows=[1])
df3

     Age  Both Sexes     Male   Female
0      0     27937.0  15646.0  12291.0
1      1      1989.0   1103.0    886.0
2      2      1376.0    797.0    579.0
3      3      1046.0    601.0    445.0
4      4       838.0    474.0    364.0
..   ...         ...      ...      ...
120  120         1.0      NaN      1.0
121  121         NaN      NaN      NaN
122  122         NaN      NaN      NaN
123  123         NaN      NaN      NaN
124  124         NaN      NaN      NaN

[125 rows x 4 columns]

In [11]:
15646.0+12291.0

27937.0